### PR TITLE
Mark saxophone as compatible with Node 16

### PR DESCRIPTION
**Pull request by philippotto**
Saxophone seems to work with node 16 which is why I added it to the list of compatible engines.

### CODE REVIEW

**Review by KevinOrfas — APPROVED** [review]

**Comment by kaminski-pawel** [comment]
Hi @matteodelabre, would you mind merging this PR? Very useful library, but it's usage was [halved](https://snyk.io/advisor/npm-package/saxophone) after Node v16 LTS was released.

**Comment by DavideMontersino** [comment]
Coming here as I'd gladly see this PR merged; our CI/CD system is not so happy about this problem either.. :(

**Comment by matteodelabre** [comment]
I will take a look at this shortly. Sorry for the delay.

**Comment by skcc75** [comment]
@matteodelabre Also Node.js 18 please

**Comment by matteodelabre** [comment]
Added as part of commit b929086f41a18842a6f7c284f21f681c185e73b6

**Pull request closed without merging**
